[project]
name = "eradiate-disort"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Vincent Leroy", email = "vincent.leroy@rayference.eu" }]
requires-python = ">=3.9,<3.13"
dependencies = ["nanodisort", "xarray", "eradiate[kernel]==1.0.*"]

[dependency-groups]
test = ["pytest>=8.4"]
docs = [
  "autodocsumm>=0.2.14",
  "shibuya",
  "sphinx",
  "sphinx-autobuild>=2021",
  "sphinx-copybutton>=0.5.2",
  "sphinx-design",
  "sphinx-iconify",
]
lint = ["ruff", "ty"]
dev = [
  "eradiate[recommended]",
  "ipykernel",
  "ipywidgets",
  "jupyterlab",
  "ruff>=0.14.9",
  "taskipy",
  { include-group = "test" },
  { include-group = "docs" },
]

[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.taskipy.tasks]
docs = { cmd = "sphinx-build -b html docs docs/_build/html", cwd = "." }
docs-clean = { cmd = "rm -rf docs/_build/", cwd = "." }
docs-serve = { cmd = "sphinx-autobuild docs docs/_build/html", cwd = "." }
docs-lock = { cmd = "uv export --frozen --no-hashes --output-file=docs/requirements.txt", cwd = "." }

[tool.pytest.ini_options]
minversion = "8.4"
testpaths = ["tests"]

[tool.uv.sources]
nanodisort = { path = "ext/nanodisort", editable = true }
eradiate = { path = "ext/eradiate", editable = true }
