# REUSE.toml
version = 1

[[annotations]]
# Default
path = "**"
SPDX-FileCopyrightText = "2026 Rayference"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
# These have per-file headers
path = ["src/**"]
